name: Build & push image to ACR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          login-server: jamilla.azurecr.io

      - run: |
          docker build . -t jamilla.azurecr.io/jamilla-fe:${{ github.sha }}
          docker push jamilla.azurecr.io/jamilla-fe:${{ github.sha }}
